### ISSUE TITLE
How To create table through flutter code?

### ISSUE THREAD

**Issue by SamarpanCoder2002** [dshukertjr/supabase-chat#1]
Hello @dshukertjr , I’m making a chat application, where each user listens to his/her own table for incoming messages. For that reason, when new users register in the app, I need to create a table after user’s phone number and do it from flutter code (not from supabase UI). I couldn’t find a way to create tables from supabase dart client. Would you be so kind as to give me advise on that?

**Comment by SamarpanCoder2002** [comment]
@dshukertjr , I eventually noticed I can create tables using a postgres client and I’m now testing this option as well. Can you confirm this is the way to go? Thx.

**Comment by dshukertjr** [comment]
Hi @SamarpanCoder2002!

In SQL, you never want to dynamically create tables. What you want to do instead is filter rows you retrieve from a table. 

In your case, you want to have a `messages` table that may look something like this:

| id  | room_id  | user_id  | text  | created_at  |
|---|---|---|---|---|
| 1  |  abc | aaa  | Hi  |  2021-08-29T11:20:50+00:00 |
| 2  |   abc  | bbb  | Hello  | 2021-08-29T11:20:51+00:00 |
|  3 |    def  | aaa  |  Nice to meet you | 2021-08-29T11:20:52+00:00 |

Where `room_id` represents the id of each chat room, `user_id` represents the user_id who posted the chat, `text` represents the actual message. You will also need separate `rooms` table to store any data related to each chat rooms and `users` table to store any data related to each users. 

With this, once a user enters a chat room, you can create a listener within Supabase to listen to any updates in that particular room. 

You can set up a listener to a particular `room_id` like this:
```dart
supabase
  .from('messages:room_id=eq.abc')
  .stream()
  .order('created_at')
  .execute()
```

Also, you can ask any Supabase related question on the [Supabase official discussion page](https://github.com/supabase/supabase/discussions). On the discussion page, I and many other people will answer your Supabase question! It's an amazing place to deepen your knowledge about Supabase!

**Comment by SamarpanCoder2002** [comment]
> Hi @SamarpanCoder2002!
> 
> In SQL, you never want to dynamically create tables. What you want to do instead is filter rows you retrieve from a table.
> 
> In your case, you want to have a `messages` table that may look something like this:
> 
> id	room_id	user_id	text	created_at
> 1	abc	aaa	Hi	2021-08-29T11:20:50+00:00
> 2	abc	bbb	Hello	2021-08-29T11:20:51+00:00
> 3	def	aaa	Nice to meet you	2021-08-29T11:20:52+00:00
> Where `room_id` represents the id of each chat room, `user_id` represents the user_id who posted the chat, `text` represents the actual message. You will also need separate `rooms` table to store any data related to each chat rooms and `users` table to store any data related to each users.
> 
> With this, once a user enters a chat room, you can create a listener within Supabase to listen to any updates in that particular room.
> 
> You can set up a listener to a particular `room_id` like this:
> 
> ```dart
> supabase
>   .from('messages:room_id=eq.abc')
>   .stream()
>   .order('created_at')
>   .execute()
> ```
> 
> Also, you can ask any Supabase related question on the [Supabase official discussion page](https://github.com/supabase/supabase/discussions). On the discussion page, I and many other people will answer your Supabase question! It's an amazing place to deepen your knowledge about Supabase!

Thanks so much for your advice! I’m trying to use the “one table design pattern” for this chat app because our stress test showed that it scales better / use less hw resources in our specific use case scenario (1:1 chats only and no messages stored on the backend after delivery). However, we will repeat our test with supabase. Thx! @dshukertjr
